- name: configuring mongodb server
  hosts: mongodb
  become: yes
  tasks:
  - name: copy mongodb repo
    copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo
  - name: install mongodb packages
    package:
      name: mongodb-org
      state: present

  - name: chage listen port
    lineinfile:
      path: /etc/mongod.conf
      regexp: '^\s*bindIp:\s*127\.0\.0\.1'
      line: '  bindIp: 0.0.0.0'
      backrefs: no
      notify: Restart MongoDB

  - name: ensure mongodb started and enabled
    service:
      name: mongodb
      state: started
      enabled: yes





  