- name: configuring mongodb server
  hosts: mongodb
  become: yes
  tasks:
  - name: copy mongodb repo
    copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo
  - name: install mongodb packages
    package:
      name: mongodb-org
      state: present

  - name: allow remote connection
    replace:
      path: /etc/mongod.conf
      regexp: 127.0.0.1
      replace: 0.0.0.0
      
  - name: ensure mongodb started and enabled
    service:
      name: mongodb
      state: started
      enabled: yes





  