- name: configure user server
  hosts: user
  become: yes
  tasks:
  - name: enable nodejs 20
    command: dnf module enable nodejs:20 -y
  - name: install nodejs 20
    package:
      name: nodejs
      state: present
  - name: add application user
    ansible.builtin.user:
      name: roboshop
      shell: /sbin/nologin     # Prevents the user from logging in interactively
      home: /app
      system: true                   # Marks this as a system account (no aging/low UID)
      state: present
      comment: "roboshop system user"
  - name: delete app dir
    file:
      path: /app
      state: absent

  - name: remove zip files
    file:
      path: /tmp/user.zip
      state: absent

  - name: Create application deployment directory
    ansible.builtin.file:
      path: /app
      state: directory
  - name: download user code
    get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/user-v3.zip
      dest: /tmp/user.zip
  - name: unzip
    unarchive:
      src: /tmp/user.zip
      dest: /app
      remote_src: yes
  - name: install dependencies
    community.general.npm:
      path: /app
  - name: copy user service
    template:
      src: user.service.j2
      dest: /etc/systemd/system/user.service
  - name: deamon reload
    systemd_service:
      name: user
      daemon_reload: true
  - name: enable and start user
    service:
      name: user
      state: restarted
      enabled: yes
    