- name: configure shipping server
  hosts: shipping
  become: yes
  tasks:
  - name: install maven & mysql
    package:
      name: "{{ item }}"
      state: present
    loop:
    - maven
    - mysql
  - name: create application user
    user:
      name: roboshop
      home: /app
      system: true
      shell: /sbin/nologin
      comment: roboshop system user
  - name: remove app dir
    file:
      path: /app
      state: absent
  - name: remove zip files
    file:
      path: /tmp/shipping.zip
      state: absent
  - name: create app dir
    file:
      path: /app
      state: directory
  - name: downlaod application code
    get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/shipping-v3.zip
      path: /tmp/shipping.zip
  - name: unzip
    unarchive:
      src: /tmp/shipping.zip
      dest: /app
      remote_src: yes
  - name: install dependies
    command: mvn clean package
    args:
      chdir: /app 
  - name: move shipping.jar
    command: mv target/shipping-1.0.jar shipping.jar 
    args:
      chdir: /app 
  - name: copy shipping service file
    template:
      name: shipping.service.j2
      dest: /etc/systemd/system/shipping.service
  - name: install python depencies
    pip:
      name: PyMySQL
      executable: pip3.9
  - name: load mysql data 
    community.mysql.mysql_db:
      state: import
      name: all
      login_user: root
      login_password: Roboshop@1
      login_host: "{{ MYSQL_HOST }}"
      traget: "{{ item }}"
    loop:
    - /app/db/schema.sql
    - /app/db/app-user.sql 
    - /app/db/master-data.sql
   
  - name: deamon reload
    systemd_service:
      name: shipping
      deamon_reload: true
  - name: enable and start shipping
    service:
      name: shipping
      state: restarted
      enabled: yes
  
