[local]
localhost

[mongodb]
mongodb.matamma.online

[redis]
redis.matamma.online

[mysql]
mysql.matamma.online

[rabbitmq]
rabbitmq.matamma.online

[catalogue]
catalogue.matamma.online

[payment]
payment.matamma.online

[shipping]
shipping.matamma.online

[cart]
cart.matamma.online

[user]
user.matamma.online