- name: creating instances in ec2
  hosts: local
  connection: local

  vars:
    instances: ["mongodb","redis","frontend","mysql","rabbitmq","catalogue","cart","user","shipping","payment"]
    image_id: ami-0220d79f3f480ecf5
    domain_name: matamma.online
    action: create

  tasks:
  - name: create instance
    amazon.aws.ec2_instance:
      name: "roboshop-{{ item }}"
      vpc_subnet_id: subnet-0bcdf0124041a31dc
      instance_type: t3.micro
      security_groups: 
        - "roboshop-{{ item }}"
        - roboshop-common
      image_id: "{{ image_id }}"
    loop: "{{ instances }}"
    register: ec2_output
    when: action == "create"

  - name: create r53 record
    amazon.aws.route53:
      state: present
      zone: matamma.online
      record: "{{ item.item }}.{{ domain_name }}"
      type: A
      ttl: 1
      value: "{{ item.instances[0].private_ip_address }}"
      overwrite: true
    loop: "{{ ec2_output.results }}"
    when: action == "create"
   
  - name: create r53 record for frontend
    amazon.aws.route53:
      state: present
      zone: matamma.online
      record: "{{ item.item }}.{{ domain_name }}"
      type: A
      ttl: 1
      value: "{{ item.instances[0].public_ip_address }}"
      overwrite: true
    loop: "{{ ec2_output.results }}"
    when: 
    - item.item == "frontend"
    - action == "create"

  - name: delete route53 records
    amazon.aws.route53:
      state: absent
      zone: matamma.online
      record: "{{ item }}.{{ domain_name }}"
      type: A
      ttl: 1
    loop: "{{ instances }}"
    when: action == "delete"
    
  - name: delete route53 records for frontend
    amazon.aws.route53:
      state: absent
      zone: matamma.online
      record: "{{ domain_name }}"
      type: A
      ttl: 1
    loop: "{{ instances }}"
    when: 
    - action == "delete"
    - item == "frontend"

  - name: delete ec2 instance
    amazon.aws.ec2_instance:
      state: absent
      name: "roboshop-{{ item }}"
    loop: "{{ instances }}"
    when: action == "delete"
   
  
