- hosts: local
  connection: local
  gather_facts: false

  vars:
    item: mongodb

  tasks:
    - amazon.aws.ec2_instance:
        name: "roboshop-{{ item }}"
        image_id: ami-0220d79f3f480ecf5
        instance_type: t3.micro
        region: us-east-1
        vpc_subnet_id: subnet-0bcdf0124041a31dc